### ISSUE TITLE
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null

### ISSUE THREAD

**Issue by AlphaJack** [pi0/cf-kv-exporter#11]
Hi, thank you for this tool!
Unfortunately, I always get this error:

```
ℹ Initializing storage...                                                                                                                                                      11:09:15 PM
✔ Using cached keys. Use --force to refresh.                                                                                                                                   11:09:15 PM
◐ Exporting 30 keys...                                                                                                                                                          11:09:15 PM
progress [===-------------------------------------] 6% | ETA: 0s | 2/30
 ERROR  The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null                                                             11:09:16 PM

  at Object.writeFile (node:internal/fs/promises:1206:5)
  at writeFile (node_modules/.pnpm/unstorage@1.10.2/node_modules/unstorage/drivers/utils/node-fs.cjs:24:23)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.setItemRaw (node_modules/.pnpm/unstorage@1.10.2/node_modules/unstorage/dist/index.cjs:250:9)
  at async concurrency (src/cli.ts:137:11)
  at async Promise.all (index 2)
  at async runParallel (src/utils.ts:37:3)
  at async Object.run (src/cli.ts:132:5)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.cjs:322:16)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.cjs:313:11)

ℹ It is likely that you have hit the Cloudflare rate limit. Please try again later in few minutes.                                                                             11:09:16 PM
ℹ Don't worry, your progress is saved and will be resumed!                                                                                                                     11:09:16 PM
 ELIFECYCLE  Command failed with exit code 1.

```

Launched as `pnpm cf-kv-exporter export --namespaceId XXX --accountId YYY --apiToken ZZZ`

**Comment by AlphaJack** [comment]
If it may help, my keys for this KV are URLs, and I can correctly see them with `wrangler kv:key list`.

However, inside the "kv_export" folder, `__export_keys__.json` contains a list of wrong keys:

```
["TEST","http:localhost:4321:blog:test1","https:example.com:projects:project-8"]
```

The program creates all the folders it needs, but it crashes with just one file (TEST):

```
.
├── __export_keys__.json
├── http/
│   └── localhost/
│       └── 4321/
│           └── blog/
├── https/
│   └── example.com/
│       └── projects/
└── TEST
```

In the example above, I would expect "test1" and "project-8" to be files.


Is it possible to have everything in one file (es. SQLite?)
